# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?q=RTGS"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?q=RTGS&limit=100"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?q=RTGS&limit=10&offset=152"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?limit=123&offset=281"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?q=Bangalore"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches/autocomplete?q=Bangalore&limit=3&offset=1236"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches?q=Bangalore"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches?q=Bangalore&limit=4"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches?q=Bangalore&limit=4&offset=0"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches?q=Delhi&limit=121&offset=172"

      - name: CURL command
        run: curl -X GET "https://dry-lake-63632.herokuapp.com/api/branches?limit=114&offset=7868"
